### PR TITLE
RFC: contributing.md

### PR DESCRIPTION
**Pull request by Fishrock123**
why: https://medium.com/node-js-javascript/codes-of-conduct-82ab2d88112d

Still work in progress, but I whipped this up for now.

Once this is done(ish) and reviewed I (or we) __will__ be applying this to ever single repo under jshttp & pillarjs, as well as active expressjs repos and express / expressjs.com themselves.

Note: this will be squashed.

### CODE REVIEW

**Comment by Fishrock123** [comment]
ugh, I feel bad for not landing this in 2014 >_<

**Comment by dougwilson** [comment]
eh :) reflect on the good and accomplishments!

**Comment by rlidwka** [comment]
> ugh, I feel bad for not landing this in 2014 >_<

I wonder, will it be landed in 2015?

**Comment by dougwilson** [comment]
I'm merging this PR for the time being :)

**Comment by Fishrock123** [comment]
Right, I suppose it may be worthwhile to revert the stuff I last added in. I'm really not sure.

**Comment by dougwilson** [comment]
Gotcha. Feel free to PR again, or whatever :) This is triggered by the new Gratipay and looking to get a team for us formed on there.

**Pull request merged**
