### PR TITLE
update travis.yml

### PR DESCRIPTION
**Pull request by rlidwka**
1\. Replace `node-0.11` with `node-0.12` and add `io.js`.

I would suggest to discuss how to test against io.js, since it's going to be updated quicker. Maybe add `iojs-1.1` (regular build, treat as stable) and `iojs` (allow failure, treat as unstable).

2\. Use docker containers, see discussion in https://github.com/mochajs/mocha/pull/1547. Jshttp tests are unlikely to require sudo, so looks safe enough. I have no idea what impact on build speed would be, but it's worth considering.

### CODE REVIEW

**Comment by dougwilson** [comment]
This is what I have been doing (disregard the 0.6-specific stuff): https://github.com/jshttp/mime-db/blob/master/.travis.yml which does the container stuff and 0.12.

As for io.js, I haven't been able to decide, because I've been asking since December what the game plan is for us, as module, to specify what versions of io.js we support. As of now, it still stands that we are not support to acknowledge io.js and just specify node.js versions. So we may end up one day with `"node": ">= 0.12 < 1 || ^1.2.0"`, which is kind of sucky.

**Comment by jonathanong** [comment]
:+1: 

at this point i would change it to `0.12`, `1`, and `2`.

**Comment by rlidwka** [comment]
@jonathanong , do you mean `iojs-1`, `iojs-2` or does travis support raw `1` number already?

**Comment by dougwilson** [comment]
Just the raw number, I believe.

**Comment by jonathanong** [comment]
yeah, nvm always supported raw numbers, but i always thought it was risky if there were ever a node v1 or v2. but now we know that's not the case.

**Comment by rlidwka** [comment]
> at this point i would change it to 0.12, 1, and 2.

done

**Pull request closed without merging**
